"use client";

import Banner from "./components/Product/Banner";
import HightLight from "./components/Product/Highlight";
import ListDiscountProduct from "./components/Product/DiscountList";
import Sidebar from "./components/Sidebar";
import List from "./components/Product/List";
import { Metadata } from "next";
import { useCallback, useState } from "react";
import ContactForm from "./components/Form";

// export const metadata: Metadata = {
//   title: "Vật tư máy",
//   description: "Generated by create next app",
// };

interface IHomeProps {}

export default function Home(props: IHomeProps) {
  const [openContact, setOpenContact] = useState<boolean>(false);
  const [productInfo, setProductInfo] = useState({});

  const handlePurchaseProduct = useCallback(
    (e) => {
      e.stopPropagation();
      e.preventDefault();
      setOpenContact(true);
      setProductInfo({ test: 1 });
    },
    [openContact, productInfo]
  );

  return (
    <div className="flex gap-10">
      <div className="w-3/12">
        <Sidebar />
      </div>
      <div className="w-9/12 flex flex-col gap-[44px]">
        <Banner />
        <HightLight />
        <ListDiscountProduct handlePurchaseProduct={handlePurchaseProduct} />
        <List handlePurchaseProduct={handlePurchaseProduct} />
        <ContactForm
          modalOpen={openContact}
          setModalOpen={setOpenContact}
          selectedProduct={productInfo}
        />
      </div>
    </div>
  );
}
